"""HTML generator for dungeon output."""

import base64
import io
import html as html_module

import cells as C
from renderer import room_polygon_vertices, room_circle_params


def generate_html(dungeon, gm_img):
    """Generate the complete HTML document for the dungeon."""
    settings = dungeon["settings"]
    name = settings["name"]
    level = settings.get("level", "1")
    cell_size = settings["cell_size"]

    # Encode map image as base64
    map_b64 = _img_to_base64(gm_img)

    # Build image map areas
    areas = _build_image_map_areas(dungeon, cell_size)

    # Build detail tables
    detail_html = _build_details(dungeon)

    css = _get_css()

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{_esc(name)}</title>
  <style>{css}</style>
</head>
<body class="codex">
  <h1>{_esc(name)} 01</h1>
  <h2>Level {_esc(level)}</h2>

<!-- BEGIN OF CONTENT -->
<div id="dungeon_map" class="dungeon_map"><img
  src="data:image/png;base64,{map_b64}"
  alt="[ dungeon map ]"
  usemap="#dungeon_areas"
/></div>
<div><map id="dungeon_areas" name="dungeon_areas">{areas}</map></div>
{detail_html}<!-- END OF CONTENT -->

  <div class="footnotes">
    <p>Generated by donjon-regen from JSON data.</p>
    <p>Original dungeon data from <a href="https://donjon.bin.sh/5e/dungeon/">donjon</a>.</p>
  </div>
</body>
</html>"""


def _esc(text):
    return html_module.escape(str(text))


def _img_to_base64(img):
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def _build_image_map_areas(dungeon, cell_size):
    """Build HTML <area> tags for the image map."""
    rooms = dungeon.get("rooms", [])
    corridor_features = dungeon.get("corridor_features", {})
    cells_data = dungeon["cells"]
    parts = []

    # Room areas
    for room in rooms:
        if room is None:
            continue
        rid = room["id"]
        shape_type = room.get("shape", "square")
        summary = room.get("contents", {}).get("summary", "")
        w = room.get("width", 0)
        h = room.get("height", 0)

        alt_text = f"Room #{rid}, {w}' x {h}', {summary}"
        href = f"#room_{rid}"

        if shape_type == "polygon":
            vertices = room_polygon_vertices(room, cell_size)
            if vertices:
                coords = ",".join(f"{vx},{vy}" for vx, vy in vertices)
                parts.append(
                    f'<area alt="{_esc(alt_text)}" coords="{coords}" '
                    f'href="{href}" shape="poly" title="{_esc(alt_text)}" />'
                )
        elif shape_type == "circle":
            west, east = room["west"], room["east"]
            north, south = room["north"], room["south"]
            x1 = west * cell_size
            y1 = north * cell_size
            x2 = (east + 1) * cell_size
            y2 = (south + 1) * cell_size
            parts.append(
                f'<area alt="{_esc(alt_text)}" coords="{x1},{y1},{x2},{y2}" '
                f'href="{href}" shape="rect" title="{_esc(alt_text)}" />'
            )
        else:
            # Square/rectangle
            west, east = room["west"], room["east"]
            north, south = room["north"], room["south"]
            x1 = west * cell_size
            y1 = north * cell_size
            x2 = (east + 1) * cell_size
            y2 = (south + 1) * cell_size
            parts.append(
                f'<area alt="{_esc(alt_text)}" coords="{x1},{y1},{x2},{y2}" '
                f'href="{href}" shape="rect" title="{_esc(alt_text)}" />'
            )

    # Door areas
    n_rows = len(cells_data)
    n_cols = len(cells_data[0])
    for row in range(n_rows):
        for col in range(n_cols):
            cell = cells_data[row][col]
            if C.has_door(cell):
                x1 = col * cell_size
                y1 = row * cell_size
                x2 = x1 + cell_size
                y2 = y1 + cell_size
                dt = C.door_type(cell)
                desc = _door_desc_from_rooms(dungeon, row, col)
                if not desc:
                    desc = dt or "door"
                parts.append(
                    f'<area alt="{_esc(desc)}" coords="{x1},{y1},{x2},{y2}" '
                    f'shape="rect" title="{_esc(desc)}" />'
                )

    # Corridor feature areas
    for key, feature in sorted(corridor_features.items()):
        summary = feature.get("summary", feature.get("detail", ""))
        for mark in feature.get("marks", []):
            col, row = mark["col"], mark["row"]
            x1 = col * cell_size
            y1 = row * cell_size
            x2 = x1 + cell_size
            y2 = y1 + cell_size
            parts.append(
                f'<area alt="{_esc(summary)}" coords="{x1},{y1},{x2},{y2}" '
                f'href="#mark_{key}" shape="rect" title="{_esc(summary)}" />'
            )

    return "".join(parts)


def _door_desc_from_rooms(dungeon, row, col):
    """Find the door description from room data matching this position."""
    rooms = dungeon.get("rooms", [])
    for room in rooms:
        if room is None:
            continue
        doors = room.get("doors", {})
        for direction, door_list in doors.items():
            for door in door_list:
                if door.get("row") == row and door.get("col") == col:
                    return door.get("desc", "")
    return ""


def _build_details(dungeon):
    """Build the HTML detail tables."""
    details = dungeon.get("details", {})
    rooms = dungeon.get("rooms", [])
    corridor_features = dungeon.get("corridor_features", {})
    parts = ['<table class="dungeon details">']

    # General section
    parts.append('<tr class="section"><td class="map_link"></td>')
    parts.append('<td class="title">General</td><td class="content"><table>')
    for key, label in [
        ("history", "History"),
        ("size", "Size"),
        ("walls", "Walls"),
        ("floor", "Floor"),
        ("temperature", "Temperature"),
        ("illumination", "Illumination"),
    ]:
        val = details.get(key)
        if val:
            parts.append(
                f'<tr class="row"><td class="title">{_esc(label)}</td>'
                f'<td class="content">{_esc(val)}</td></tr>'
            )
    parts.append("</table></td></tr>")

    # Corridor Features section
    if corridor_features:
        parts.append('<tr class="section"><td class="map_link"></td>')
        parts.append(
            '<td class="title">Corridor Features</td><td class="content"><table>'
        )
        for key in sorted(corridor_features.keys()):
            feat = corridor_features[key]
            detail = feat.get("detail", feat.get("summary", ""))
            parts.append(
                f'<tr class="row"><td class="title">'
                f'<span id="mark_{key}">{_esc(key)}</span></td>'
                f'<td class="content">{_esc(detail)}</td></tr>'
            )
        parts.append("</table></td></tr>")

    # Room sections
    for room in rooms:
        if room is None:
            continue
        rid = room["id"]
        parts.append('<tr class="section">')
        parts.append(
            f'<td class="map_link">'
            f'<a href="#dungeon_map" title="to Map">&uarr;</a></td>'
        )
        parts.append(
            f'<td class="title"><span id="room_{rid}">Room #{rid}</span></td>'
        )
        parts.append('<td class="content"><table>')

        # Doors
        doors = room.get("doors", {})
        for direction in ["north", "south", "east", "west"]:
            door_list = doors.get(direction, [])
            for i, door in enumerate(door_list):
                dir_label = direction.capitalize() + " Entry"
                if len(door_list) > 1:
                    dir_label += f" #{i + 1}"
                desc = door.get("desc", "")
                content = f"<p>{_esc(desc)}</p>"

                # Trap on door
                trap = door.get("trap")
                if trap:
                    content += f'<p class="icon">&#9417; &nbsp; {_esc(trap)}</p>'

                # Connection to another room
                out_id = door.get("out_id")
                if out_id:
                    content += (
                        f'<p class="icon">&rarr; &nbsp; '
                        f'Leads to <a href="#room_{out_id}">room #{out_id}</a></p>'
                    )

                parts.append(
                    f'<tr class="row"><td class="door">{_esc(dir_label)}</td>'
                    f'<td class="content">{content}</td></tr>'
                )

        # Room contents
        contents = room.get("contents", {})
        summary = contents.get("summary", "")
        detail = contents.get("detail", {})

        if isinstance(detail, dict):
            # Room features
            features = detail.get("room_features")
            if features:
                parts.append(
                    f'<tr class="row"><td class="title">Room Features</td>'
                    f'<td class="content"><p>{_esc(features)}</p></td></tr>'
                )

            # Trap
            trap = detail.get("trap")
            if trap:
                if isinstance(trap, list):
                    trap_text = "\n".join(trap)
                else:
                    trap_text = trap
                parts.append(
                    f'<tr class="row"><td class="title">Trap</td>'
                    f'<td class="content"><p>{_esc(trap_text)}</p></td></tr>'
                )

            # Trick
            trick = detail.get("trick")
            if trick:
                parts.append(
                    f'<tr class="row"><td class="title">Trick</td>'
                    f'<td class="content"><p>{_esc(trick)}</p></td></tr>'
                )

            # Hidden treasure
            treasure = detail.get("hidden_treasure")
            if treasure:
                if isinstance(treasure, list):
                    treasure_parts = []
                    for item in treasure:
                        if item == "--":
                            treasure_parts.append("<hr />")
                        else:
                            treasure_parts.append(f"<p>{_esc(item)}</p>")
                    treasure_html = "".join(treasure_parts)
                else:
                    treasure_html = f"<p>{_esc(treasure)}</p>"
                parts.append(
                    f'<tr class="row"><td class="title">Hidden Treasure</td>'
                    f'<td class="content">{treasure_html}</td></tr>'
                )
        elif summary and summary != "Empty":
            parts.append(
                f'<tr class="row"><td class="title">{_esc(summary)}</td>'
                f'<td class="content">&nbsp;</td></tr>'
            )
        else:
            parts.append(
                f'<tr class="row"><td class="title">Empty</td>'
                f'<td class="content">&nbsp;</td></tr>'
            )

        parts.append("</table></td></tr>")

    parts.append("</table>")
    return "\n".join(parts)


def _get_css():
    """Return the CSS for the dungeon HTML page."""
    return """
  body.codex {
    margin: 0px;
    padding: 2ex 2em;
    font-family: 'Asul', sans-serif;
  }
  body.codex h1 {
    text-align: center;
    font-size: 200%; font-weight: bold;
  }
  body.codex h2 {
    text-align: center;
    font-size: 150%; font-weight: bold;
  }
  table.dungeon {
    margin: 2ex auto;
    border: none; border-collapse: collapse;
  }
  div.dungeon_map {
    margin: 2ex 2em;
    text-align: center;
    white-space: nowrap;
  }
  div.dungeon_key {
    margin: 2ex 2em;
    text-align: center;
  }
  div.footnotes p {
    margin: 2ex 2em;
    text-align: center;
  }
  table.dungeon.details {
    border-top: 1px solid;
    border-color: #cccccc;
  }
  table.dungeon.details tr.section {
    padding: 1ex 1em;
    border-bottom: 1px solid;
    border-color: #cccccc;
  }
  table.dungeon.details tr.section > td.map_link a {
    display: none;
    color: black;
    text-decoration: none;
  }
  table.dungeon.details tr.section:hover > td.map_link a {
    display: initial;
  }
  table.dungeon.details tr.section > td.title {
    font-size: 120%;
    line-height: 200%;
  }
  table.dungeon.details td {
    padding: 1ex 1em;
    vertical-align: top;
  }
  table.dungeon.details td.title {
    min-width: 10em;
    text-align: right;
    font-weight: bold;
  }
  table.dungeon.details td.door {
    min-width: 10em;
    text-align: right;
    font-style: italic;
  }
  table.dungeon.details td.content {
    width: 100%;
  }
  table.dungeon.details td.content table {
    border: none; border-collapse: collapse;
  }
  table.dungeon.details td.content p {
    margin: 0px; padding: 0px;
  }
  table.dungeon.details td.content hr {
    margin: 0px;
    border: none; border-top: 1px solid;
    border-color: #cccccc;
  }
  table.dungeon.details td.content > * + * {
    margin-top: 1ex !important;
  }
  table.dungeon.details tr.section:hover > td {
    background: #dedede;
  }
  table.dungeon.details tr.row:hover td {
    background: white;
  }
  @media print {
    body.codex { padding: 0px 1ex; font-size: 60%; }
    div.dungeon_map img { max-width: 100%; }
    div.dungeon_key img { max-width: 100%; }
  }
"""
